package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFD0E4FF)
val md_theme_dark_onPrimary = Color(0xFF00315B)
val md_theme_dark_primaryContainer = Color(0xFF004A77)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_secondary = Color(0xFFC4C7C5)
val md_theme_dark_onSecondary = Color(0xFF2D2F31)
val md_theme_dark_secondaryContainer = Color(0xFF3F484E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF2D2F31)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C7C5)
val md_theme_dark_outline = Color(0xFF444746)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0061A4)
val md_theme_dark_surfaceTint = Color(0xFFD0E4FF)
val md_theme_dark_outlineVariant = Color(0xFF8E918F)
val md_theme_dark_scrim = Color(0xFF000000)
